### ISSUE TITLE
Bin releases of `slight`

### ISSUE THREAD

**Issue by devigned** [deislabs/spiderlightning#182]
We should start building and publishing releases for `slight`, so that folks don't need to build bins themselves.

We need to add a release action that is triggered by a semantic version tag that would build `slight` bins targeting the major OS/Arch combinations.

**Comment by danbugs** [comment]
made a test release just now, but we should integrate that onto the CI, so I'll leave this open until then~

**Comment by Mossaka** [comment]
Closed by #214
