### ISSUE TITLE
allow multiple secret-stores (i.e., per capability)

### ISSUE THREAD

**Issue by danbugs** [deislabs/spiderlightning#91]
**Describe the solution you'd like**
Currently, we only allow the user to set one `secret_store` in the toml file. That means that, in a multi-capability example, all capabilities will need to search for their configs in the exact same way. We'd like to change this behaviour to allow capability specific secret configuration. 

**Additional context**
n/a

**Comment by Mossaka** [comment]
Closed by https://github.com/deislabs/spiderlightning/pull/222
